### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [65]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))#first random class second random method

array([[0.98714039, 0.47713292, 0.66116303, 0.51712134],
       [0.22728022, 0.06273451, 0.36931876, 0.61503162],
       [0.4830561 , 0.43655886, 0.19205129, 0.92024717]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)#lower and upper bounds inclusive 10 numbers

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0.],
       [0., 1.]])

### Array Attributes

In [69]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim  number of dimensions
a3.ndim

3

In [ ]:
# shape  2 2D array these array shapes 2 rows and 2 columns
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size  number of elements
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize size of each element in bytes 8 bytes 1 byte = 8 bits
a3.itemsize

8

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype int 32 4 bytes int 64 8 bytes 
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [2]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[36., 32., 70.],
       [22., 37.,  2.],
       [19., 16., 89.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
#np.max(a1)
#np.min(a1)
#np.sum(a1)
np.prod(a1,axis=0) #multiplication of columns axis=1 row wise multiplication

array([15048., 18944., 12460.])

In [ ]:
# mean/median/std/var
#np.mean(a1)
#np.median(a1)
#np.std(a1)
#np.var(a1,axis=1) variance row wise

array([ 290.66666667,  205.55555556, 1137.55555556])

In [12]:
# trigonomoetric functions
np.sin(a1)

array([[-0.99177885,  0.55142668,  0.77389068],
       [-0.00885131, -0.64353813,  0.90929743],
       [ 0.14987721, -0.28790332,  0.86006941]])

In [13]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [16]:
# log and exponents
#a1
#np.log(a1)
np.exp(a1)

array([[4.31123155e+15, 7.89629602e+13, 2.51543867e+30],
       [3.58491285e+09, 1.17191424e+16, 7.38905610e+00],
       [1.78482301e+08, 8.88611052e+06, 4.48961282e+38]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100) 
#np.ceil(np.random.random((2,3))*100) 6.9 floor 6.0 ceil 7.0 

array([[76., 65.,  3.],
       [68., 50., 31.]])

### Indexing and Slicing

In [21]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2[1,0]

np.int64(4)

In [25]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
a3[1,0,1]

np.int64(5)

In [27]:
a3[1,1,0]

np.int64(6)

In [29]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1[2:5:2]

array([2, 4])

In [31]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#a2[0,:]
#a2[1:,1:3]
#a2[::2,::3]
#a2[::2,1::2]
#a2[1,::3]
#a2[0:2,1:]
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [42]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
a2[1,::3]

array([4, 7])

In [44]:
a2[0,:]

array([0, 1, 2, 3])

In [45]:
a2[:,2]

array([ 2,  6, 10])

In [46]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [47]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [49]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [50]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [51]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [54]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3): #apply with individual elements
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [57]:
# reshape

In [58]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel n dimensional to 1 dimensional
a3.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [32]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [62]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [63]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [35]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]